name: CI tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:

  Run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']
    steps:

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest
